// examples/nextjs-example.tsx
// Next.js component example for Quill Reveal Slide
'use client';

import { useEffect, useRef, useState } from 'react';
import dynamic from 'next/dynamic';
import Head from 'next/head';

// Dynamically import Quill to avoid SSR issues
const ReactQuill = dynamic(() => import('react-quill'), { ssr: false });
import 'react-quill/dist/quill.snow.css';

export default function QuillRevealSlidePage() {
  const quillRef = useRef(null);
  const [exportedHTML, setExportedHTML] = useState('');
  const [fragments, setFragments] = useState([]);
  const [isClient, setIsClient] = useState(false);

  useEffect(() => {
    setIsClient(true);
    
    // Import Quill modules dynamically
    const loadQuillModules = async () => {
      if (typeof window !== 'undefined') {
        const Quill = (await import('quill')).default;
        const { FragmentBlot, RevealExporter, i18n } = await import('quill-reveal-slide');
        
        // Register the fragment format
        Quill.register('formats/fragment', FragmentBlot);
        
        // Configure custom toolbar
        const toolbarOptions = [
          ['bold', 'italic', 'underline'],
          ['link', 'blockquote'],
          [{ 'list': 'ordered'}, { 'list': 'bullet' }],
          [{ 'header': [1, 2, 3, false] }],
          [{ 'custom-fragment': '🎭 Fragment' }]
        ];

        // Custom toolbar handler
        const handleFragmentCreation = (quill) => {
          const selection = quill.getSelection();
          if (!selection || selection.length === 0) {
            alert('Please select text first!');
            return;
          }

          const selectedText = quill.getText(selection.index, selection.length);
          const effect = prompt('Enter fragment effect:', 'fade-in');
          const order = prompt('Enter fragment order (optional):');
          
          if (effect) {
            const fragmentData = {
              effect,
              index: order ? parseInt(order) : undefined
            };

            quill.format('fragment', fragmentData);
            
            const newFragment = {
              id: `fragment-${Date.now()}`,
              text: selectedText,
              ...fragmentData
            };
            
            setFragments(prev => [...prev, newFragment]);
            quill.emitter.emit('fragment-created', newFragment);
          }
        };

        // Store references for export functions
        window.quillInstance = quillRef.current?.getEditor();
        window.RevealExporter = RevealExporter;
        window.handleFragmentCreation = handleFragmentCreation;
      }
    };

    loadQuillModules();
  }, []);

  const exportSlide = () => {
    if (window.quillInstance && window.RevealExporter) {
      const contents = window.quillInstance.getContents();
      const slideHTML = window.RevealExporter.generateRevealSlide(contents, "Next.js Generated Slide");
      setExportedHTML(slideHTML);
    }
  };

  const exportPresentation = () => {
    if (window.quillInstance && window.RevealExporter) {
      const contents = window.quillInstance.getContents();
      const slideHTML = window.RevealExporter.generateRevealSlide(contents, "Next.js Generated Slide");
      const presentationHTML = window.RevealExporter.generateCompletePresentation([slideHTML]);
      setExportedHTML(presentationHTML);
    }
  };

  const handleChange = (content, delta, source, editor) => {
    // Handle content changes if needed
  };

  const modules = {
    toolbar: {
      container: [
        ['bold', 'italic', 'underline'],
        ['link', 'blockquote'],
        [{ 'list': 'ordered'}, { 'list': 'bullet' }],
        [{ 'header': [1, 2, 3, false] }],
        [{ 'custom-fragment': '🎭 Fragment' }]
      ],
      handlers: {
        'custom-fragment': function() {
          if (window.handleFragmentCreation) {
            window.handleFragmentCreation(this.quill);
          }
        }
      }
    }
  };

  if (!isClient) {
    return <div>Loading...</div>;
  }

  return (
    <>
      <Head>
        <title>Quill Reveal Slide - Next.js Example</title>
        <meta name="description" content="Next.js integration example for Quill Reveal Slide" />
        <link href="/quill-reveal-slide.css" rel="stylesheet" />
      </Head>
      
      <div style={{ maxWidth: '1000px', margin: '40px auto', padding: '20px' }}>
        <div style={{ 
          background: 'white', 
          borderRadius: '16px', 
          padding: '40px', 
          boxShadow: '0 8px 32px rgba(0,0,0,0.1)' 
        }}>
          <h1 style={{ 
            color: '#2c3e50', 
            marginBottom: '10px',
            fontSize: '2.5rem',
            textAlign: 'center'
          }}>
            🎭 Next.js + Quill Reveal Slide
          </h1>
          
          <p style={{ 
            color: '#7f8c8d', 
            marginBottom: '40px',
            textAlign: 'center',
            fontSize: '1.2rem'
          }}>
            Server-side rendering compatible fragment editor
          </p>
          
          <div style={{ 
            background: 'linear-gradient(135deg, #e8f5e8 0%, #f0f9f0 100%)', 
            borderLeft: '4px solid #27ae60', 
            padding: '20px', 
            marginBottom: '30px',
            borderRadius: '0 12px 12px 0' 
          }}>
            <h3 style={{ color: '#27ae60', marginBottom: '15px' }}>
              🚀 Next.js Integration Features
            </h3>
            <ul style={{ paddingLeft: '20px' }}>
              <li><strong>SSR Compatible:</strong> Dynamically loaded to avoid hydration issues</li>
              <li><strong>TypeScript Ready:</strong> Full type support included</li>
              <li><strong>Production Optimized:</strong> Code splitting and lazy loading</li>
              <li><strong>SEO Friendly:</strong> Works with Next.js App Router</li>
            </ul>
          </div>

          <div style={{ marginBottom: '30px' }}>
            <ReactQuill
              ref={quillRef}
              theme="snow"
              modules={modules}
              onChange={handleChange}
              defaultValue={`Welcome to Next.js + Quill Reveal Slide! 

This example shows how to integrate Quill Reveal Slide with Next.js applications.

Key benefits of this integration:
• Server-side rendering compatible
• Automatic code splitting
• TypeScript support
• Production optimized

Select any text above and click the Fragment button to create animated elements for your Reveal.js presentations.

Perfect for creating educational content, marketing presentations, or interactive storytelling!`}
              style={{ 
                height: '300px',
                marginBottom: '50px'
              }}
            />
          </div>
          
          {/* Fragments List */}
          {fragments.length > 0 && (
            <div style={{ 
              background: '#f8f9fa', 
              padding: '20px', 
              borderRadius: '12px',
              marginBottom: '30px'
            }}>
              <h3 style={{ marginBottom: '15px', color: '#2c3e50' }}>
                📋 Created Fragments ({fragments.length})
              </h3>
              <div style={{ display: 'grid', gap: '10px' }}>
                {fragments.map((fragment, index) => (
                  <div 
                    key={fragment.id}
                    style={{ 
                      background: 'white',
                      padding: '15px',
                      borderRadius: '8px',
                      borderLeft: '3px solid #3498db',
                      boxShadow: '0 2px 4px rgba(0,0,0,0.1)'
                    }}
                  >
                    <div style={{ 
                      fontWeight: 'bold', 
                      color: '#3498db',
                      marginBottom: '5px'
                    }}>
                      {fragment.effect}
                      {fragment.index && ` (order: ${fragment.index})`}
                    </div>
                    <div style={{ 
                      fontSize: '14px', 
                      color: '#7f8c8d' 
                    }}>
                      "{fragment.text.length > 80 ? fragment.text.substring(0, 80) + '...' : fragment.text}"
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}
          
          {/* Export Section */}
          <div style={{ 
            background: 'linear-gradient(135deg, #f8f9fa 0%, #e9ecef 100%)', 
            padding: '30px', 
            borderRadius: '12px' 
          }}>
            <h3 style={{ 
              marginBottom: '20px', 
              color: '#2c3e50',
              fontSize: '1.4rem'
            }}>
              📤 Export to Reveal.js
            </h3>
            
            <div style={{ 
              display: 'grid', 
              gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', 
              gap: '15px', 
              marginBottom: '20px' 
            }}>
              <button 
                onClick={exportSlide}
                style={{ 
                  padding: '15px 25px', 
                  border: 'none', 
                  borderRadius: '10px', 
                  background: 'linear-gradient(135deg, #3498db 0%, #2980b9 100%)', 
                  color: 'white', 
                  cursor: 'pointer',
                  fontWeight: '600',
                  fontSize: '14px',
                  transition: 'transform 0.2s ease'
                }}
                onMouseOver={(e) => e.target.style.transform = 'translateY(-2px)'}
                onMouseOut={(e) => e.target.style.transform = 'translateY(0)'}
              >
                📄 Export Single Slide
              </button>
              
              <button 
                onClick={exportPresentation}
                style={{ 
                  padding: '15px 25px', 
                  border: 'none', 
                  borderRadius: '10px', 
                  background: 'linear-gradient(135deg, #27ae60 0%, #229954 100%)', 
                  color: 'white', 
                  cursor: 'pointer',
                  fontWeight: '600',
                  fontSize: '14px',
                  transition: 'transform 0.2s ease'
                }}
                onMouseOver={(e) => e.target.style.transform = 'translateY(-2px)'}
                onMouseOut={(e) => e.target.style.transform = 'translateY(0)'}
              >
                📊 Export Full Presentation
              </button>
            </div>
            
            {exportedHTML && (
              <div>
                <h4 style={{ marginBottom: '10px', color: '#2c3e50' }}>
                  Generated HTML:
                </h4>
                <pre style={{ 
                  background: '#2c3e50', 
                  color: '#ecf0f1', 
                  padding: '20px', 
                  borderRadius: '8px', 
                  overflow: 'auto', 
                  maxHeight: '300px',
                  fontSize: '12px',
                  lineHeight: '1.4'
                }}>
                  {exportedHTML}
                </pre>
              </div>
            )}
          </div>
        </div>
      </div>
    </>
  );
}

// Usage instructions for package.json
/*
Add these dependencies to your Next.js project:

{
  "dependencies": {
    "next": "^14.0.0",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "react-quill": "^2.0.0",
    "quill": "^2.0.3",
    "quill-reveal-slide": "^1.0.0"
  }
}

And add this to your next.config.js:

module.exports = {
  transpilePackages: ['quill-reveal-slide'],
  webpack: (config) => {
    config.resolve.alias = {
      ...config.resolve.alias,
      'quill': 'quill/dist/quill.js'
    };
    return config;
  }
};
*/

// examples/vue-example.vue
<!-- Vue component example for Quill Reveal Slide -->
<template>
  <div class="container">
    <div class="editor-wrapper">
      <h1 class="title">🎭 Vue Quill Reveal Slide</h1>
      <p class="subtitle">Create animated presentation fragments in Vue.js</p>

      <div class="instructions">
        <strong>How to use:</strong>
        <ol>
          <li>Select text in the editor</li>
          <li>Click the 🎭 Fragment button</li>
          <li>Choose effect and order in the modal</li>
          <li>Export to Reveal.js format</li>
        </ol>
      </div>

      <div ref="editor" class="editor"></div>

      <!-- Fragment List -->
      <div v-if="fragments.length > 0" class="fragments-list">
        <h3>Created Fragments:</h3>
        <ul>
          <li v-for="fragment in fragments" :key="fragment.id">
            <strong>{{ fragment.effect }}</strong>
            <span v-if="fragment.index"> (order: {{ fragment.index }})</span>:
            "{{ fragment.text.substring(0, 50) }}..."
          </li>
        </ul>
      </div>

      <!-- Export Section -->
      <div class="export-section">
        <h3>Export Options</h3>
        <div class="buttons">
          <button @click="exportSlide" class="btn btn-primary">
            Export Slide HTML
          </button>
          <button @click="exportPresentation" class="btn btn-success">
            Export Full Presentation
          </button>
          <button @click="clearEditor" class="btn btn-danger">
            Clear Editor
          </button>
        </div>

        <pre v-if="exportedHTML" class="output">{{ exportedHTML }}</pre>
      </div>
    </div>

    <!-- Fragment Creation Modal -->
    <div v-if="showModal" class="modal-overlay" @click="closeModal">
      <div class="modal-dialog" @click.stop>
        <h3>🎭 {{ $t("dialog.createFragment") }}</h3>
        <div class="form-group">
          <label>{{ $t("dialog.effect") }}:</label>
          <select v-model="selectedEffect" class="form-control">
            <option value="fade-in">fade-in</option>
            <option value="fade-up">fade-up</option>
            <option value="fade-down">fade-down</option>
            <option value="fade-left">fade-left</option>
            <option value="fade-right">fade-right</option>
            <option value="fade-out">fade-out</option>
            <option value="highlight-red">highlight-red</option>
            <option value="highlight-green">highlight-green</option>
            <option value="highlight-blue">highlight-blue</option>
            <option value="grow">grow</option>
            <option value="shrink">shrink</option>
            <option value="strike">strike</option>
          </select>
        </div>
        <div class="form-group">
          <label>{{ $t("dialog.order") }} ({{ $t("dialog.optional") }}):</label>
          <input
            v-model.number="selectedOrder"
            type="number"
            min="1"
            max="100"
            class="form-control"
          />
        </div>
        <div class="modal-buttons">
          <button @click="closeModal" class="btn btn-secondary">
            {{ $t("dialog.cancel") }}
          </button>
          <button @click="createFragment" class="btn btn-primary">
            {{ $t("dialog.create") }}
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import Quill from "quill";
import { FragmentBlot, RevealExporter, i18n } from "quill-reveal-slide";
import "quill/dist/quill.snow.css";
import "quill-reveal-slide/style.css";

// Register the fragment format
Quill.register({
  "formats/fragment": FragmentBlot,
});

export default {
  name: "QuillFragmentEditor",
  data() {
    return {
      quill: null,
      showModal: false,
      selectedEffect: "fade-in",
      selectedOrder: null,
      currentSelection: null,
      fragments: [],
      exportedHTML: "",
      currentLanguage: "en",
    };
  },
  mounted() {
    this.initializeQuill();
  },
  beforeDestroy() {
    if (this.quill) {
      this.quill = null;
    }
  },
  methods: {
    initializeQuill() {
      this.quill = new Quill(this.$refs.editor, {
        theme: "snow",
        modules: {
          toolbar: {
            container: [
              ["bold", "italic", "underline"],
              ["link"],
              [{ list: "ordered" }, { list: "bullet" }],
              [{ "custom-fragment": "🎭 Fragment" }],
            ],
            handlers: {
              "custom-fragment": () => this.handleFragmentCreation(),
            },
          },
        },
      });

      // Listen to fragment events
      this.quill.on("fragment-created", (data) => {
        console.log("Fragment created:", data);
      });

      // Add sample content
      this.quill.setText(`Welcome to Vue + Quill Reveal Slide!

This is a sample paragraph. Select this text and click the Fragment button to make it animated.

Vue.js integration makes it easy to handle events and manage state.

Try creating fragments with different effects and orders!`);
    },

    handleFragmentCreation() {
      const selection = this.quill.getSelection();
      if (!selection || selection.length === 0) {
        alert(i18n.t("error.noSelection"));
        return;
      }

      this.currentSelection = selection;
      this.showModal = true;
    },

    createFragment() {
      if (!this.currentSelection) return;

      const fragmentData = {
        effect: this.selectedEffect,
        index: this.selectedOrder || undefined,
      };

      this.quill.format("fragment", fragmentData);

      // Get selected text
      const selectedText = this.quill.getText(
        this.currentSelection.index,
        this.currentSelection.length
      );

      // Add to fragments list
      const newFragment = {
        id: `fragment-${Date.now()}`,
        text: selectedText,
        ...fragmentData,
      };

      this.fragments.push(newFragment);

      // Emit event
      this.quill.emitter.emit("fragment-created", newFragment);

      this.closeModal();
    },

    closeModal() {
      this.showModal = false;
      this.currentSelection = null;
      this.selectedEffect = "fade-in";
      this.selectedOrder = null;
    },

    exportSlide() {
      const contents = this.quill.getContents();
      const slideHTML = RevealExporter.generateRevealSlide(
        contents,
        "Vue Generated Slide"
      );
      this.exportedHTML = slideHTML;
    },

    exportPresentation() {
      const contents = this.quill.getContents();
      const slideHTML = RevealExporter.generateRevealSlide(
        contents,
        "Vue Generated Slide"
      );
      const presentationHTML = RevealExporter.generateCompletePresentation([
        slideHTML,
      ]);
      this.exportedHTML = presentationHTML;
    },

    clearEditor() {
      this.quill.setText("");
      this.fragments = [];
      this.exportedHTML = "";
    },

    $t(key) {
      return i18n.t(key);
    },
  },
};
</script>

<style scoped>
.container {
  max-width: 800px;
  margin: 40px auto;
  padding: 20px;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
}

.editor-wrapper {
  background: white;
  border-radius: 12px;
  padding: 30px;
  box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
}

.title {
  color: #2c3e50;
  margin-bottom: 10px;
}

.subtitle {
  color: #7f8c8d;
  margin-bottom: 30px;
}

.instructions {
  background: #e8f5e8;
  border-left: 4px solid #27ae60;
  padding: 15px;
  margin-bottom: 20px;
  border-radius: 0 6px 6px 0;
}

.editor {
  height: 300px;
  margin-bottom: 20px;
}

.fragments-list {
  margin-bottom: 20px;
}

.fragments-list h3 {
  margin-bottom: 10px;
}

.fragments-list ul {
  list-style-type: disc;
  padding-left: 20px;
}

.fragments-list li {
  margin-bottom: 5px;
}

.export-section {
  margin-top: 30px;
  padding: 20px;
  background: #f8f9fa;
  border-radius: 8px;
}

.buttons {
  display: flex;
  gap: 10px;
  margin-bottom: 15px;
  flex-wrap: wrap;
}

.btn {
  padding: 8px 16px;
  border: none;
  border-radius: 6px;
  cursor: pointer;
  font-weight: 500;
  transition: background-color 0.2s;
}

.btn-primary {
  background: #3498db;
  color: white;
}

.btn-primary:hover {
  background: #2980b9;
}

.btn-success {
  background: #27ae60;
  color: white;
}

.btn-success:hover {
  background: #229954;
}

.btn-danger {
  background: #e74c3c;
  color: white;
}

.btn-danger:hover {
  background: #c0392b;
}

.btn-secondary {
  background: #95a5a6;
  color: white;
}

.btn-secondary:hover {
  background: #7f8c8d;
}

.output {
  background: #2c3e50;
  color: #ecf0f1;
  padding: 15px;
  border-radius: 6px;
  overflow: auto;
  max-height: 200px;
  font-size: 12px;
  margin-top: 15px;
}

/* Modal Styles */
.modal-overlay {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background: rgba(0, 0, 0, 0.5);
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 10000;
}

.modal-dialog {
  background: white;
  padding: 30px;
  border-radius: 12px;
  max-width: 400px;
  width: 90%;
  box-shadow: 0 10px 25px rgba(0, 0, 0, 0.2);
}

.modal-dialog h3 {
  margin: 0 0 20px 0;
  color: #2c3e50;
}

.form-group {
  margin-bottom: 15px;
}

.form-group label {
  display: block;
  margin-bottom: 5px;
  font-weight: 500;
}

.form-control {
  width: 100%;
  padding: 8px;
  border: 1px solid #ddd;
  border-radius: 4px;
  box-sizing: border-box;
}

.modal-buttons {
  display: flex;
  gap: 10px;
  justify-content: flex-end;
  margin-top: 20px;
}
</style>
